"""empty message

Revision ID: 14442d4dd6ce
Revises: 3a067e07ecf7
Create Date: 2015-03-22 22:53:54.822849

"""

# revision identifiers, used by Alembic.
revision = '14442d4dd6ce'
down_revision = '3a067e07ecf7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeslot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('once', sa.Boolean(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduled_call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application', sa.Integer(), nullable=True),
    sa.Column('scheduledAt', sa.DateTime(), nullable=True),
    sa.Column('failed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['application'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_calls',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_call_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scheduled_call_id'], ['scheduled_call.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'scheduled_call_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_calls')
    op.drop_table('scheduled_call')
    op.drop_table('timeslot')
    ### end Alembic commands ###
