"""empty message

Revision ID: 2d25928d01fb
Revises: 3a067e07ecf7
Create Date: 2015-03-22 19:04:15.237448

"""

# revision identifiers, used by Alembic.
revision = '2d25928d01fb'
down_revision = '3a067e07ecf7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    op.execute('COMMIT')  # See https://bitbucket.org/zzzeek/alembic/issue/123
    op.execute("""
ALTER TYPE STAGES ADD value 'review_reply' after 'reply_received';
""")


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
