"""empty message

Revision ID: 2e857a13e0d1
Revises: 138abff72a80
Create Date: 2015-04-02 20:39:40.870215

"""

# revision identifiers, used by Alembic.
revision = '2e857a13e0d1'
down_revision = '138abff72a80'

from alembic import op
import sqlalchemy as sa

from app import user_datastore
from app.models import User, Role




def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('COMMIT')
    role = user_datastore.find_or_create_role("reviewer")
    reviewers = User.query.outerjoin("roles"
                    ).filter(User.roles == None)

    for reviewer in reviewers:
        user_datastore.add_role_to_user(reviewer, role)

    user_datastore.commit()

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
