"""empty message

Revision ID: 2f1f29f30500
Revises: 5109364cd6c3
Create Date: 2015-04-11 23:27:26.107701

"""

# revision identifiers, used by Alembic.
revision = '2f1f29f30500'
down_revision = '5109364cd6c3'

from alembic import op
import sqlalchemy as sa
from app import db
from sqlalchemy.sql.expression import bindparam

from app.utils import generate_fancy_name


class DummyApplication(db.Model):
    __tablename__ = "application"
    __table_args__ = dict(extend_existing=True)
    id = db.Column(db.Integer, primary_key=True)
    anon_name = db.Column(db.String)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('anon_name', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'application', ['anon_name'])
    ### end Alembic commands ###

    db.Model.metadata.bind = op.get_bind()

    connection = op.get_bind()
    Session = sa.orm.sessionmaker()
    session = Session(bind=connection)

    op.execute("COMMIT")

    for x in session.query(DummyApplication).values(DummyApplication.id):
        session.query(DummyApplication
                        ).filter(DummyApplication.id==x[0]
                        ).update({"anon_name": generate_fancy_name()})
    session.commit()


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'application', type_='unique')
    op.drop_column('application', 'anon_name')
    ### end Alembic commands ###
