"""empty message

Revision ID: 3c8997667609
Revises: None
Create Date: 2015-03-10 00:05:46.780690

"""

# revision identifiers, used by Alembic.
revision = '3c8997667609'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('changedStageAt', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('anon_content', sa.Text(), nullable=True),
    sa.Column('fizzbuzz', sa.Text(), nullable=True),
    sa.Column('stage', sa.Enum('processing', 'to_anon', 'in_review', 'email_send', 'reply_received', 'skyped', 'accepted', 'rejected', 'grant_review', 'grant_accepted', 'grant_rejected', 'archived', 'inactive'), nullable=True),
    sa.Column('batch', sa.String(length=64), nullable=True),
    sa.Column('grant', sa.Boolean(), nullable=True),
    sa.Column('grant_content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anon_content'),
    sa.UniqueConstraint('content'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('fizzbuzz'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('role', sa.Enum('admin', 'moderator', 'reviewer'), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'application_id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=120), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('stage', sa.Enum('processing', 'to_anon', 'in_review', 'email_send', 'reply_received', 'skyped', 'accepted', 'rejected', 'grant_review', 'grant_accepted', 'grant_rejected', 'archived', 'inactive'), nullable=True),
    sa.Column('question', sa.Boolean(), nullable=True),
    sa.Column('application_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author')
    )
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('author', sa.String(length=120), nullable=True),
    sa.Column('stage', sa.Enum('processing', 'to_anon', 'in_review', 'email_send', 'reply_received', 'skyped', 'accepted', 'rejected', 'grant_review', 'grant_accepted', 'grant_rejected', 'archived', 'inactive'), nullable=True),
    sa.Column('incoming', sa.Boolean(), nullable=True),
    sa.Column('application_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('anon_content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anon_content'),
    sa.UniqueConstraint('author'),
    sa.UniqueConstraint('content')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email')
    op.drop_table('comment')
    op.drop_table('members')
    op.drop_table('user')
    op.drop_table('application')
    ### end Alembic commands ###
