"""empty message

Revision ID: 3e1b4f9b6c40
Revises: 2f1f29f30500
Create Date: 2015-05-07 21:07:16.189202

"""

# revision identifiers, used by Alembic.
revision = '3e1b4f9b6c40'
down_revision = '2f1f29f30500'

from alembic import op
import sqlalchemy as sa


def upgrade():

    op.execute('COMMIT')
    op.execute("""ALTER TYPE "STAGES" ADD value 'deposit_paid' after 'accepted';
""")



def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
