"""empty message

Revision ID: 40269cf5b94b
Revises: 20b34c762e03
Create Date: 2015-03-07 23:12:42.067772

"""

# revision identifiers, used by Alembic.
revision = '40269cf5b94b'
down_revision = '3bc00259fcee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###

    op.create_table('members',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('application_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'application_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    ### end Alembic commands ###
