"""empty message

Revision ID: 42b37a601685
Revises: 40269cf5b94b
Create Date: 2015-03-08 17:33:30.837587

"""

# revision identifiers, used by Alembic.
revision = '42b37a601685'
down_revision = '40269cf5b94b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isActive', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isActive')
    ### end Alembic commands ###
