"""empty message

Revision ID: 432c40f9d1de
Revises: 4a069dd52dd0
Create Date: 2015-03-25 14:26:36.139847

"""

# revision identifiers, used by Alembic.
revision = '432c40f9d1de'
down_revision = '4a069dd52dd0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_call', sa.Column('calendar_id', sa.String(length=255), nullable=True))
    ### end Alembic commands ###

    op.execute('COMMIT')  # See https://bitbucket.org/zzzeek/alembic/issue/123
    # Appareantly the name as done by SQLAlchemy/Alembic has _quotes in the name_.
    op.execute("""
ALTER TYPE "STAGES" ADD value 'skype_scheduled' after 'review_reply';
""")
    op.execute("""
ALTER TYPE "STAGES" ADD value 'schedule_skype' after 'review_reply';
""")



def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_call', 'calendar_id')
    ### end Alembic commands ###
