"""empty message

Revision ID: 5109364cd6c3
Revises: 2c8531376b77
Create Date: 2015-04-12 02:07:28.055383

"""

# revision identifiers, used by Alembic.
revision = '5109364cd6c3'
down_revision = '2c8531376b77'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE application RENAME COLUMN anonymizer TO anonymizer_id")
    op.execute("ALTER TABLE comment RENAME COLUMN application TO application_id")
    op.execute("ALTER TABLE email RENAME COLUMN application TO application_id")
    op.execute("ALTER TABLE email RENAME COLUMN author TO author_id")
    op.execute("ALTER TABLE scheduled_call RENAME COLUMN application TO application_id")
    op.execute("ALTER TABLE timeslot RENAME COLUMN \"user\" TO user_id")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE application RENAME COLUMN anonymizer_id TO anonymizer")
    op.execute("ALTER TABLE comment RENAME COLUMN application_id TO application")
    op.execute("ALTER TABLE email RENAME COLUMN application_id TO application")
    op.execute("ALTER TABLE email RENAME COLUMN author_id TO author")
    op.execute("ALTER TABLE scheduled_call RENAME COLUMN application_id TO application")
    op.execute("ALTER TABLE timeslot RENAME COLUMN user_id TO user")
    ### end Alembic commands ###
