"""empty message

Revision ID: d22d7a67429
Revises: 3c8997667609
Create Date: 2015-03-10 21:02:22.734314

"""

# revision identifiers, used by Alembic.
revision = 'd22d7a67429'
down_revision = '3c8997667609'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.add_column(u'user', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column(u'user', sa.Column('password', sa.String(length=40), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'user', sa.Column('role', sa.VARCHAR(length=9), nullable=True))
    op.drop_column(u'user', 'password')
    op.drop_column(u'user', 'active')
    op.drop_table('roles_users')
    op.drop_table('role')
    ### end Alembic commands ###
